#!/usr/bin/env python3
"""
Generate a weekly summary (top 5 stories) from daily digest files in a week folder.
Parses existing daily digests, extracts articles with relevance scores,
and outputs a weekly-summary.md with the top 5.

Usage:
    python scripts/generate_weekly_summary.py digests/2026-03-23_to_2026-03-29/
"""

import re
import sys
from pathlib import Path


def parse_articles_from_digest(filepath: Path) -> list[dict]:
    """Extract ranked articles from a daily digest markdown file."""
    text = filepath.read_text(encoding="utf-8")
    articles = []

    # Split by article sections: ## 1. [Title](url)
    pattern = re.compile(
        r"^## \d+\.\s+\[(.+?)\]\((.+?)\)\s*\n"
        r"\*\*Source:\*\*\s*(.+?)\s*\|\s*(.+?)\s*\|\s*\*\*Relevance:\*\*\s*([\d.]+)/10\s*\n"
        r"\n>\s*(.+?)\n"
        r"(?:\n\*\*Why it matters:\*\*\s*(.+?)\n)?",
        re.MULTILINE,
    )

    for m in pattern.finditer(text):
        articles.append({
            "title": m.group(1),
            "url": m.group(2),
            "source": m.group(3).strip(),
            "date": m.group(4).strip(),
            "score": float(m.group(5)),
            "summary": m.group(6).strip(),
            "why_important": m.group(7).strip() if m.group(7) else "",
            "digest_date": filepath.stem,  # e.g. "2026-03-28"
        })

    return articles


def deduplicate_by_title(articles: list[dict]) -> list[dict]:
    """Remove articles covering the same story (similar titles)."""
    seen_titles = []
    unique = []
    for article in articles:
        title_lower = article["title"].lower()
        # Check if this title is too similar to one we've already kept
        is_dup = False
        for seen in seen_titles:
            # Simple word overlap check
            words_a = set(title_lower.split())
            words_b = set(seen.split())
            overlap = len(words_a & words_b) / max(len(words_a | words_b), 1)
            if overlap > 0.6:
                is_dup = True
                break
        if not is_dup:
            unique.append(article)
            seen_titles.append(title_lower)
    return unique


def generate_summary(week_dir: Path) -> None:
    """Generate weekly-summary.md in the given week directory."""
    # Collect all daily digests
    daily_files = sorted(week_dir.glob("????-??-??.md"))
    if not daily_files:
        print(f"No daily digests found in {week_dir}")
        return

    # Parse all articles from all daily digests
    all_articles = []
    for f in daily_files:
        all_articles.extend(parse_articles_from_digest(f))

    if not all_articles:
        print(f"No articles parsed from {week_dir}")
        return

    # Sort by relevance score (descending), deduplicate similar stories
    all_articles.sort(key=lambda a: a["score"], reverse=True)
    unique_articles = deduplicate_by_title(all_articles)
    top5 = unique_articles[:5]

    # Determine week range from folder name
    folder_name = week_dir.name  # e.g. "2026-03-23_to_2026-03-29"
    parts = folder_name.split("_to_")
    week_start = parts[0]
    week_end = parts[1] if len(parts) > 1 else "unknown"

    # Generate markdown
    lines = [
        f"# Weekly Summary — {week_start} to {week_end}",
        "",
        f"*Top 5 stories from {len(daily_files)} daily digests "
        f"({len(all_articles)} total articles reviewed)*",
        "",
        "---",
        "",
    ]

    for i, article in enumerate(top5, 1):
        lines.append(f"## {i}. [{article['title']}]({article['url']})")
        lines.append(
            f"**Source:** {article['source']} | {article['date']} "
            f"| **Relevance:** {article['score']}/10 "
            f"| *From {article['digest_date']} digest*"
        )
        lines.append("")
        lines.append(f"> {article['summary']}")
        lines.append("")
        if article["why_important"]:
            lines.append(f"**Why it matters:** {article['why_important']}")
            lines.append("")
        lines.append("---")
        lines.append("")

    lines.append(
        "*Generated by NewsUpdate Agent — Weekly Summary*"
    )
    lines.append("")

    output_path = week_dir / "weekly-summary.md"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/generate_weekly_summary.py <week_folder>")
        sys.exit(1)

    week_dir = Path(sys.argv[1])
    if not week_dir.is_dir():
        print(f"Not a directory: {week_dir}")
        sys.exit(1)

    generate_summary(week_dir)
